# Generated by Django 4.2.7 on 2023-11-11 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_passenger_passenger_code_alter_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
