# Generated by Django 4.2.7 on 2023-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_passenger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='dni',
            field=models.CharField(default=1061, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
