# Generated by Django 4.2.7 on 2023-11-19 16:34

from django.db import migrations, models
import django.db.models.deletion
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_passenger_dni_passenger_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('transportation_type', models.CharField(choices=[(travel.models.TransportationType['BUS'], 'Bus'), (travel.models.TransportationType['TRAIN'], 'Tren'), (travel.models.TransportationType['PLANE'], 'Avión'), (travel.models.TransportationType['CAR'], 'Carro')], max_length=50)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('trip_status', models.CharField(choices=[(travel.models.TripStatus['ACTIVE'], 'Active'), (travel.models.TripStatus['CANCELLED'], 'Cancelled'), (travel.models.TripStatus['COMPLETED'], 'Completed')], default='Active', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[(travel.models.PaymentMethod['CASH'], 'Efectivo'), (travel.models.PaymentMethod['CARD'], 'Tarjeta'), (travel.models.PaymentMethod['PAYPAL'], 'PayPal')], max_length=10)),
                ('installments', models.IntegerField(default=1)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Terminado')], default='Pendiente', max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.trip')),
            ],
        ),
    ]
