# Generated by Django 4.2.7 on 2023-11-19 16:47

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_trip_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[(travel.models.TripStatus['ACTIVE'], 'Activo'), (travel.models.TripStatus['CANCELLED'], 'Cancelado'), (travel.models.TripStatus['COMPLETED'], 'Completed')], default='Activo', max_length=20),
        ),
    ]
