# Generated by Django 4.2.7 on 2023-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_trip_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transportation_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Tren'), ('PLANE', 'Avión'), ('CAR', 'Carro')], max_length=50),
        ),
    ]
