# Generated by Django 4.2.7 on 2023-11-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_trip_transportation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado')], default='Activo', max_length=20),
        ),
    ]
