# Generated by Django 4.2.7 on 2023-11-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_sale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
