# Generated by Django 4.2.7 on 2023-11-26 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_remove_sale_arrival_date_remove_sale_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('destination', models.CharField(max_length=100)),
                ('excursion_names', models.TextField()),
                ('dates_and_times', models.DateTimeField()),
                ('hotels', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.trip')),
            ],
        ),
    ]
