# Generated by Django 4.2.7 on 2023-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Terminado')], default='Pendiente', max_length=20),
        ),
    ]
