# Generated by Django 4.2.7 on 2023-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_sale_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='role',
            field=models.CharField(choices=[('TRAVELER', 'VIAJERO'), ('PAYER', 'PAGADOR'), ('BOTH', 'AMBOS')], default='VIAJERO', max_length=10),
        ),
    ]
