# Generated by Django 4.2.6 on 2023-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_alter_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('PAYPAL', 'Transferencia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportation_type',
            field=models.CharField(choices=[('BUS', 'Colectivo'), ('TRAIN', 'Trafi'), ('PLANE', 'Avión'), ('CAR', 'Auto')], max_length=50),
        ),
    ]
